### ISSUE TITLE
Question: How did you make transpiled Haxe code to hsluv.py?

### ISSUE THREAD

**Issue by medicalwei** [hsluv/hsluv-python#10]
My intention is to [package hsluv-python to Debian due to a dependency][1], but our policy requires us [not to package generated code but to rebuild them][2].

I tried to run Haxe by myself, and found that the formats of source code are different, although every function looks like having the same structure:

![screenshot from 2018-03-19 20-54-41](https://user-images.githubusercontent.com/74481/37629166-3e0e4752-2c18-11e8-9656-4b908a244d2a.png)

What I found that the function name and packaging are different than generated code, also the format is a lot cleaner and readable, and I think you did not just remove dead code as you said in the header of hsluv.py.

Could you tell me the details about this?

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891391
[2]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=882723#35

**Comment by boronine** [comment]
I only used dead code removal as an example of how the Haxe-generated code was cleaned up manually. The clean-up also included variable renaming and formatting changes. There is no way to automatically generate hsluv-python code, so you should definitely just use it as-is. I think for the purpose of the Debian policy, you can consider `hsluv.py` to be *derived* from generated code rather than *being* generated code.

It would be great to see hsluv-python packaged for Debian, thank you for taking the time to do it :)

**Comment by medicalwei** [comment]
Thanks for the explanation! I am closing this issue. If there's any problem regarding to Debian policy and stuff, I might reopen this.
