### ISSUE TITLE
Git tags / next release: 5.0.0?

### ISSUE THREAD

**Issue by hartwork** [hsluv/hsluv-python#21]
Hi!

It came to my attention that the two most recent releases to PyPI — 0.0.1 and 0.0.2 — do not have Git tags here. Since https://github.com/hsluv/hsluv-python/releases went up to `v4.0.2` for husl, it takes (a) a different namespace or (b) jumping to something bigger than `v4.0.3`. My recommendation is to use `5.0.0` on PyPI and `v5.0.0` for the next Git tag.

What do you think?

Best, Sebastian

**Comment by boronine** [comment]
This is a good idea. Looking forward to releasing 5.0.0 shortly!

**Comment by hartwork** [comment]
Awesome! :tada:

**Comment by boronine** [comment]
I just released version 5.0.0. Huge thanks to @hartwork for your patience and professionalism, huge thanks to @scratchmex for your energy and diligence! Because Python is number 1 language for scientific programming, even small improvements to this repo will have great positive ripple effects for the project as a whole.

@hartwork I sent you an invite to receive write access to all HSLuv repos. If you ever find time to contribute to the project in the future, I don't want you to be slowed down by the PR process.

Thanks again guys!

**Comment by hartwork** [comment]
Very kind — thank you!
